language: node_js
matrix:
  include:
    - node_js: node # Current
      env: REPORT_COVERAGE=true
    - node_js: lts/* # Latest LTS
      env: NPM_DEPLOY=true
    - node_js: lts/carbon
    - node_js: lts/boron # Minimum required
install:
  - npm install --loglevel http # Prevent timeouts for inactivity
before_script:
  - npm run lint
script:
  - npm test -- --coverage
  - '[[ "$REPORT_COVERAGE" != true ]] || codecov'
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: demvsystems/fuzzy-date # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
    - $HOME/.npm
